# Information about website
favicon:
  small: /images/favicon-16x16.png
  medium: /images/favicon-32x32.png
  apple_touch_icon: /images/apple-touch-icon.png
  safari_pinned_tab: /images/logo.svg
# Direction of static files
css: css
js: js
images: images
# Data format
full_data_format: DD/MM/YYYY HH:mm
time_format: HH:mm
data_format: DD/MM/YYYY
# Customization
default_post_icon: fas fa-align-justify
canvas_nest: true